version: '3'

services:
  app:
    build: .
    image: dotagem_app:latest
    container_name: dotagem-app
    ports:
      - "3000:3000"
    environment:
      DB_HOST               : ${DB_HOST}
      DB_PORT               : ${DB_PORT}
      DB_USER               : ${DB_USER}
      DB_PASS               : ${DB_PASS}
      SECRET_KEY_BASE       : ${SECRET_KEY_BASE}
      BASE_URL              : ${BASE_URL}
      TELEGRAM_BOT_TOKEN    : ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_USERNAME : ${TELEGRAM_BOT_USERNAME}
      TELEGRAM_BOT_CHANNEL  : ${TELEGRAM_BOT_CHANNEL}
      STEAM_TOKEN           : ${STEAM_TOKEN}
    depends_on:
      - db
      - cache

  db:
    image: postgres:15
    container_name: dotagem-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB       : dotagem
      POSTGRES_USER     : ${DB_USER}
      POSTGRES_PASSWORD : ${DB_PASS}
    ports:
      - "5432:5432"

  cache:
    image: redis:latest
    container_name: dotagem-cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data

volumes:
  postgres_data: {}
  cache: {}
