name: Run tests and push image

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]
  # Allows this workflow to be called from the deploy one
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    # Postgres container
    services:
      postgres:
        image: postgres:14.5-bullseye
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: dotagem-test
          POSTGRES_USER: dotagem
          POSTGRES_PASSWORD: password
          RAILS_ENV: test
          DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check out the repo
      - uses: actions/checkout@v3

      # Redis
      - uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 7

      # Ruby and (cached) gems
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true

      # Override the default configuration
      - name: Configure database
        run: |
          rm config/database.yml
          touch config/database.yml
          echo "test:" > config/database.yml
          echo "  adapter: postgresql" >> config/database.yml
          echo "  pool: 5" >> config/database.yml
          echo "  host: localhost" >> config/database.yml
          echo "  port: 5432" >> config/database.yml
          echo "  username: dotagem" >> config/database.yml
          echo "  password: password" >> config/database.yml
          echo "  database: dotagem-test" >> config/database.yml

      - name: Run Rspec
        run: bundle exec rspec

  push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: "https://forge.cschuijt.nl"
          username: casper
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: 'forge.cschuijt.nl/dotagem/dotagem:latest'
